baseURL = "https://dsuwala.github.io"
title = "Dominik Suwala"
theme = ["hugo-video", "gokarna"]
languageCode = "en"
defaultContentLanguage = "en"
themesdir = "./themes"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Dominik Suwala"
  description = "Computational physicist, python programmer, upwork freelancer"
  #avatarURL = ""
  #AvatarAltText = ""
  #avatarSize = ""
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/dominik-suwa%C5%82a-432b04237/"},
    {name = "github", url = "https://github.com/dsuwala"},
    {name = "upwork", url = "https://www.upwork.com/freelancers/~01143f983a2105fbfa"},
  ]
  metaKeywords = ["physics", "high performance computing", "freelancer", "upwork"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
