baseURL = 'https://dsuwala.github.io/'
languageCode = 'en-us'
title = "Dominik Suwala's homepage"
theme = ["hugo-video", "hugo-digital-garden-theme"]
themesdir = "./themes"
copyright = "Dominik Suwala ©"

[params]
  name = "Dominik Suwala"
  description = "Computational physicist, freelancer"
  initials = "DS"
  googleAnalytics = ""

  [[params.social]]
    name = "Github"
    link = "https://github.com/dsuwala/"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/dominik-suwa%C5%82a-432b04237/"
    icon = "fab fa-linkedin-in"

  [[params.social]]
    name = "Upwork"
    link = "https://www.upwork.com/freelancers/~01143f983a2105fbfa"
    icon = ""


[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Personal garden"
    url = "/garden/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'